version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - Teakowa
  labels:
  - "\U0001F4E6 Type/Dependencies"
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.1
