name: Docker Build

on: 
  push:
    paths-ignore:
      - 'README.md'

jobs:
  publish-to-docker-io:
    name: Publish to Docker.io
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fspnetwork/php
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        tags: "edge"