name: Docker Build

on:
  release:
    types: [published]

jobs:
  publish-to-docker-io:
    name: Publish to Docker.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: fspnetwork/php
        cache: fspnetwork/php
        auto_tag: true
    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: fspnetwork/php
        cache: fspnetwork/php
        tags: latest