name: Docker Build

on:
  release:
    types: [published]

jobs:
  publish-to-docker-io:
    name: Publish to Docker.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: fspnetwork/php
        auto_tag: true
    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: fspnetwork/php
        tags: latest
  publish-to-github-pkg:
    name: Publish to GitHub Package Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.GITHUB_USERNAME }}
        password: ${{ secrets.GITHUB_PR_TOKEN }}
        registry: docker.pkg.github.com
        repository: fspnet/php/php
        auto_tag: true
    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.GITHUB_USERNAME }}
        password: ${{ secrets.GITHUB_PR_TOKEN }}
        registry: docker.pkg.github.com
        repository: fspnet/php/php
        tags: latest